apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base 참조
resources:
- ../../base
- ingress.yaml

# dev 환경 라벨
labels:
- pairs:
    environment: dev
    branch: dev

# dev 환경 annotations
commonAnnotations:
  argocd.argoproj.io/tracking-id: dev-argocd

# dev 환경 패치
patches:
- path: patches/configmap-patch.yaml
- path: patches/rbac-patch.yaml
- path: patches/server-patch.yaml
- path: patches/resource-limits.yaml

# dev 환경용 ConfigMap 생성
configMapGenerator:
- name: argocd-dev-config
  literals:
  - ENV=dev
  - LOG_LEVEL=debug
  - GIT_BRANCH=dev

# 네임스페이스 접두사 없음 (표준 ArgoCD 이름 사용)
namePrefix: ""

# dev 환경 특화 이미지 태그
images:
- name: quay.io/argoproj/argocd
  newTag: v2.9.3

# 리소스 변환 (dev 환경용 최적화)
replicas:
- name: argocd-server
  count: 1
- name: argocd-application-controller
  count: 1
- name: argocd-repo-server
  count: 1 