apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-server-config
data:
  application-dev.yml: |
    spring:
      application:
        name: feed-server
      profiles:
        active: dev
      datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
      h2:
        console:
          enabled: true
          path: /h2-console
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      actuator:
        endpoints:
          web:
            exposure:
              include: health,info,metrics,prometheus,env,configprops
        endpoint:
          health:
            show-details: always
            probes:
              enabled: true
        health:
          livenessstate:
            enabled: true
          readinessstate:
            enabled: true
    
    server:
      port: 8080
      servlet:
        context-path: /
    
    logging:
      level:
        com.example.feedserver: DEBUG
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus,env,configprops
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true 