apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-server
spec:
  replicas: 1  # Dev 환경에서는 리소스 절약
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: feed-server
        env:
        - name: APP_ENV
          value: "development"
        - name: DEBUG_MODE
          value: "true"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -Dspring.profiles.active=dev"
        resources:
          requests:
            memory: "1Gi"  # Spring Boot 요구사항
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m" 