# Feed Server Development Environment
# Argo Rollouts Blue/Green 배포 - 개발 환경

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base 참조
resources:
- ../../base
- namespace.yaml
- ingress.yaml

# 네임스페이스 설정
namespace: feed-server-dev

# 개발 환경 라벨 추가
labels:
- pairs:
    branch: dev
    environment: dev

# 개발 환경 어노테이션
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  config.kubernetes.io/target-environment: development

# 환경별 설정 오버라이드
configMapGenerator:
- literals:
  - ENVIRONMENT=dev
  - DEBUG=true
  - LOG_LEVEL=debug
  - ENABLE_METRICS=true
  - ROLLOUT_STRATEGY=blue-green
  - IMAGE_TAG=latest
  name: feed-server-env-config

# 개발 환경 패치
patches:
- path: rollout-patch.yaml
  target:
    kind: Rollout
    name: feed-server-rollout
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: feed-server-config

# 개발 환경 이미지 설정 (CI/CD에서 자동으로 업데이트됨)
images:
- name: feed-server
  newName: 421114334882.dkr.ecr.ap-northeast-2.amazonaws.com/feed-server
  newTag: b8ff15a9bb9ac37d1cdbdc38e4ca06ebff473478
