apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: guestbook-base

commonLabels:
  app.kubernetes.io/name: guestbook
  app.kubernetes.io/part-of: guestbook-suite

resources:
- deployment.yaml
- service.yaml

namespace: guestbook

# 공통 이미지 태그
images:
- name: gcr.io/google-samples/gb-frontend
  newTag: "v4" 