apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base 참조
resources:
- ../../base
- ingress.yaml

# prod 환경 라벨
commonLabels:
  environment: prod
  branch: main

# prod 환경 annotations
commonAnnotations:
  argocd.argoproj.io/tracking-id: prod-argocd

# prod 환경 패치
patchesStrategicMerge:
- patches/configmap-patch.yaml
- patches/rbac-patch.yaml
- patches/server-patch.yaml
- patches/resource-limits.yaml

# prod 환경용 ConfigMap 생성
configMapGenerator:
- name: argocd-prod-config
  literals:
  - ENV=prod
  - LOG_LEVEL=info
  - GIT_BRANCH=main

# 네임스페이스 접두사 없음 (표준 ArgoCD 이름 사용)
namePrefix: ""

# prod 환경 특화 이미지 태그 (안정 버전)
images:
- name: quay.io/argoproj/argocd
  newTag: v2.9.3

# 리소스 변환 (prod 환경용 고가용성)
replicas:
- name: argocd-server
  count: 2
- name: argocd-application-controller
  count: 1
- name: argocd-repo-server
  count: 2 