apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  scope: Cluster
  group: crd.k8s.amazonaws.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                securityGroups:
                  type: array
                  items:
                    type: string
                subnet:
                  type: string
  names:
    plural: eniconfigs
    singular: eniconfig
    kind: ENIConfig
