apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-server
  labels:
    app: feed-server
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-server
  template:
    metadata:
      labels:
        app: feed-server
        version: v1
    spec:
      containers:
      - name: feed-server
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_NAME
          value: "Feed Server"
        - name: APP_VERSION
          value: "v1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi" 
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 