# Feed Server Base Kustomization
# Argo Rollouts Blue/Green 배포를 위한 기본 리소스

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 기본 리소스
resources:
- rollout.yaml           # Argo Rollouts Rollout
- service.yaml           # Active Service
- service-preview.yaml   # Preview Service (Blue/Green용)
- configmap.yaml         # 기본 ConfigMap

# 공통 라벨
labels:
- pairs:
    app: feed-server
    app.kubernetes.io/name: feed-server
    app.kubernetes.io/part-of: feed-server-suite

# 공통 어노테이션
commonAnnotations:
  config.kubernetes.io/origin-source: "Feed Server App - Argo Rollouts Blue/Green"

# 기본 이미지 설정 (overlay에서 오버라이드됨)
images:
- name: feed-server
  newName: feed-server
  newTag: "latest" 