apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: feed-server-rollout
  labels:
    app: feed-server
    app.kubernetes.io/name: feed-server
    app.kubernetes.io/part-of: feed-server-suite
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: feed-server
      previewService: feed-server-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      # prePromotionAnalysis:
      #   templates:
      #   - templateName: simple-health-check
      #   args:
      #   - name: service-name
      #     value: feed-server-preview
      #   - name: namespace
      #     value: feed-server-dev
  selector:
    matchLabels:
      app: feed-server
  template:
    metadata:
      labels:
        app: feed-server
        version: v1
        app.kubernetes.io/name: feed-server
        app.kubernetes.io/part-of: feed-server-suite
    spec:
      containers:
      - name: feed-server
        image: feed-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: APP_NAME
          value: "Feed Server"
        - name: APP_VERSION
          value: "v1.0.0"
        - name: DEPLOYMENT_TYPE
          value: "Blue-Green with Argo Rollouts"
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  revisionHistoryLimit: 3 