apiVersion: v1
kind: Service
metadata:
  name: feed-server
  labels:
    app: feed-server
    app.kubernetes.io/name: feed-server
    app.kubernetes.io/part-of: feed-server-suite
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: feed-server 