# BubblePool Development Environment
# Argo Rollouts Blue/Green 배포 - 개발 환경

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base 참조
resources:
- ../../base
- namespace.yaml
- ingress.yaml

# 네임스페이스 설정
namespace: bubblepool-dev

# 개발 환경 라벨 추가
commonLabels:
  environment: dev
  branch: dev

# 개발 환경 어노테이션
commonAnnotations:
  config.kubernetes.io/target-environment: "development"
  argocd.argoproj.io/sync-wave: "1"

# 환경별 설정 오버라이드
configMapGenerator:
- name: bubblepool-env-config
  literals:
  - ENVIRONMENT=dev
  - DEBUG=true
  - LOG_LEVEL=debug
  - ENABLE_METRICS=true
  - ROLLOUT_STRATEGY=blue-green

# 개발 환경 패치
patchesStrategicMerge:
- rollout-patch.yaml

# 이미지 태그 설정 (개발 환경)
images:
- name: nginx
  newName: nginx
  newTag: 1.22-alpine 