# Development Environment Rollout Patch
# 개발 환경에 특화된 Rollout 설정

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bubblepool-rollout
spec:
  # 개발 환경에서는 더 빠른 배포
  strategy:
    blueGreen:
      scaleDownDelaySeconds: 10  # 개발 환경에서는 빠른 정리
      autoPromotionEnabled: false # 수동 승인으로 테스트 가능
      
  template:
    metadata:
      labels:
        # 개발 환경 추가 라벨
        environment: dev
        branch: dev
    spec:
      containers:
      - name: bubblepool
        # 개발 환경 특화 환경 변수
        env:
        - name: APP_NAME
          value: "BubblePool"
        - name: APP_VERSION
          value: "v1.0.0"
        - name: DEPLOYMENT_TYPE
          value: "Blue-Green with Argo Rollouts"
        - name: ENVIRONMENT
          value: "development"
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
        
        # 개발 환경에서는 더 관대한 리소스
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
            
        # 개발 환경에서는 더 빠른 헬스체크
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15  # 더 빠른 시작
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 