apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt 프로덕션 서버
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@barodream.com
    # 개인키를 저장할 시크릿 이름
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # HTTP-01 챌린지 방식 사용
    - http01:
        ingress:
          class: alb
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt 스테이징 서버 (테스트용)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@barodream.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: alb 