apiVersion: v1
kind: Pod
metadata:
  name: deploy-pod1
  namespace: dev-csi-file-pv
  labels:
    app: efs-test
    component: writer
spec:
  securityContext:
    fsGroup: 1000  # 파일 시스템 그룹 ID 설정
    runAsUser: 1000  # 컨테이너 실행 사용자 ID
    runAsGroup: 1000  # 컨테이너 실행 그룹 ID
  containers:
  - name: app
    image: centos:8  # 특정 버전 태그 사용
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /dpod1/out; sleep 5; done"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
    - name: persistent-storage1
      mountPath: /dpod1
      readOnly: false  # 읽기/쓰기 모드로 마운트
    livenessProbe:
      exec:
        command: ["ls", "/dpod1/out"]
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      exec:
        command: ["ls", "/dpod1/out"]
      initialDelaySeconds: 5
      periodSeconds: 10
  volumes:
  - name: persistent-storage1
    persistentVolumeClaim:
      claimName: efs-pv-claim
      readOnly: false  # 읽기/쓰기 모드로 볼륨 마운트
  nodeSelector:
    kubernetes.io/os: linux  # 리눅스 노드에만 스케줄링
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
