apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv-claim
  namespace: dev-csi-file-pv
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
    volume.kubernetes.io/selected-node: ""  # Fargate 호환성을 위해 비워둠
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi  # 스토리지 상한선 설정 (선택사항)
  volumeMode: Filesystem
