apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Git 저장소 설정
  repositories: |
    - url: https://github.com/your-org/platform
      type: git
      name: platform-repo
  
  # 애플리케이션 기본 설정
  application.instanceLabelKey: argocd.argoproj.io/instance
  
  # 서버 설정
  server.insecure: "true"  # dev 환경에서는 HTTP 허용
  
  # 자동 동기화 설정
  timeout.reconciliation: 180s
  
  # Git 폴링 간격
  timeout.hard.reconciliation: 0s
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # 성능 최적화 설정
  application.operation.processors: "10"
  controller.status.processors: "20"
  controller.operation.processors: "10"
  
  # Git 설정
  reposerver.parallelism.limit: "10" 