apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 네임스페이스 설정
namespace: argocd

# 원격 ArgoCD 공식 설치 매니페스트
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
- configmap.yaml
# - rbac-config.yaml  # 패치로 처리하여 충돌 방지

# 공통 라벨
labels:
- pairs:
    app.kubernetes.io/instance: argocd
    environment: dev

# ConfigMap 패치 (충돌 방지를 위해 제거)
# patches (deprecated patchesStrategicMerge 제거):
# - |
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
#     namespace: argocd
#   data:
#     url: http://argocd-server.argocd.svc.cluster.local

# 리소스 이름 접두사 제거 (ArgoCD 표준 이름 사용)
# namePrefix: ""

# 이미지 태그 고정 (안정성을 위해)
images:
- name: quay.io/argoproj/argocd
  newTag: v2.9.3 