apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-config
    app.kubernetes.io/part-of: argo-rollouts
data:
  # Argo Rollouts Controller 설정
  # 자세한 설정 옵션: https://argo-rollouts.readthedocs.io/en/stable/features/controller/
  
  # 메트릭 제공자 설정 (Prometheus)
  # metrics.yaml: |
  #   providers:
  #     - name: prometheus
  #       type: prometheus
  #       url: http://prometheus.monitoring.svc.cluster.local:9090
  
  # 알림 설정
  # notifications.yaml: |
  #   service:
  #     slack:
  #       token: $slack-token
  
  # 트래픽 관리 설정 (ALB, Istio 등)
  # traffic-management.yaml: |
  #   trafficRouterPlugins:
  #     - name: "argoproj-labs/rollouts-plugin-trafficrouter-aws-app-mesh"
  #       location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-aws-app-mesh/releases/download/v0.1.0/aws-app-mesh-trafficrouter-linux-amd64"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-notification-config
    app.kubernetes.io/part-of: argo-rollouts
data:
  # 알림 템플릿 설정
  template.app-deployed: |
    message: |
      {{if eq .rollout.status.phase "Healthy"}} ✅ {{else}} ❌ {{end}} Application {{.rollout.metadata.name}} is now {{.rollout.status.phase}}.
      Revision: {{.rollout.status.currentPodHash}}
  
  template.app-health-degraded: |
    message: |
      ⚠️ Application {{.rollout.metadata.name}} has degraded health.
      Revision: {{.rollout.status.currentPodHash}}
  
  # 트리거 설정
  trigger.on-deployed: |
    - when: rollout.status.phase in ['Healthy']
      send: [app-deployed]
  
  trigger.on-health-degraded: |
    - when: rollout.status.phase in ['Degraded']
      send: [app-health-degraded] 