apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argo-rollouts-base
  annotations:
    config.kubernetes.io/local-config: "true"

# 원격 리소스에서 공식 Argo Rollouts 매니페스트 가져오기
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
  - configmap.yaml

# 공통 레이블 적용
commonLabels:
  app.kubernetes.io/name: argo-rollouts
  app.kubernetes.io/part-of: argo
  app.kubernetes.io/version: v1.7.2
  app.kubernetes.io/managed-by: kustomize

# 네임스페이스 설정
namespace: argo-rollouts

# 이미지 태그 설정 (필요시 오버라이드)
images:
  - name: quay.io/argoproj/argo-rollouts
    newTag: v1.7.2

# 리소스 이름에 접두사/접미사 추가 (선택사항)
# namePrefix: dev-
# nameSuffix: -rollouts

# ConfigMap 생성기 (추가 설정 파일용)
configMapGenerator:
  - name: argo-rollouts-dashboard-config
    literals:
      - ARGO_ROLLOUTS_DASHBOARD_BASE_URL=/rollouts
      - ARGO_ROLLOUTS_DASHBOARD_ROOT_PATH=/rollouts
    options:
      labels:
        app.kubernetes.io/name: argo-rollouts-dashboard-config
        app.kubernetes.io/component: dashboard

# 패치 적용 (리소스 제한, 보안 설정 등)
patchesStrategicMerge: []
  # - patches/resource-limits.yaml
  # - patches/security-context.yaml

# JSON 패치 (세밀한 수정용)
patchesJson6902: []
  # - target:
  #     version: v1
  #     kind: Deployment
  #     name: argo-rollouts
  #   path: patches/deployment-patch.yaml 