# Launch templates are managed by EKS node groups

  name = "eks-2ecc05ed-1f40-964e-63ef-7d37607e9280"

  network_interfaces {
    device_index       = "0"
    ipv4_address_count = "0"
    ipv4_prefix_count  = "0"
    ipv6_address_count = "0"
    ipv6_prefix_count  = "0"
    network_card_index = "0"
    security_groups    = ["sg-09c0a3bf75b21cb6b"]
  }

  region = "ap-northeast-2"

  tags = {
    "eks:cluster-name"   = "test-eks-cluster"
    "eks:nodegroup-name" = "test-eks-cluster-nodegroup"
  }

  tags_all = {
    "eks:cluster-name"   = "test-eks-cluster"
    "eks:nodegroup-name" = "test-eks-cluster-nodegroup"
  }

  user_data = "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKCi0tLy8KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQ7IGNoYXJzZXQ9InVzLWFzY2lpIgojIS9iaW4vYmFzaApzZXQgLWV4CkI2NF9DTFVTVEVSX0NBPUxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVVJDVkVORFFXVXlaMEYzU1VKQlowbEpUMnM0UkVJcmVXOXZaVzkzUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkR1ZFVlVUVUpGUjBFeFZVVUtRWGhOUzJFelZtbGFXRXAxV2xoU2JHTjZRV1ZHZHpCNVRsUkJNMDFVVlhkTlZGVTFUVlJrWVVaM01IcE9WRUV6VFZSTmQwMXFRVEJOVkdSaFRVSlZlQXBGZWtGU1FtZE9Wa0pCVFZSRGJYUXhXVzFXZVdKdFZqQmFXRTEzWjJkRmFVMUJNRWREVTNGSFUwbGlNMFJSUlVKQlVWVkJRVFJKUWtSM1FYZG5aMFZMQ2tGdlNVSkJVVU16VVZkTlEwWnZORGxhVGxVNFdXRnpSbkF6YzNoaWNVb3JZbVowVDFoVVoyYzFiblZpYm5wdE1HY3lhRkpsVEZVeGRrdzNOV3R6VG5JS1kyZElXWFJLZFM5bFFWUklSMWs0WlRsWlozbFFUUzlWU1dacFJGa3pURGR3Y0RWaFJtTjRlVGhaY2xBdlozVmxWREZZYjBsWFJFZFlaRzFzVGpCV05ncDVTMEYzZG5kQlNGaHhhQzl2YzFsdlpqVkJVV2s1ZVdKWFozbHBZMlpXWVhKbVdpOTNlbmg2U1dSbVNYQlpVVEEyY1VWNVpUZzFLM2N2ZFRGUFpHUlVDbWN3T1hRMWNIVlJXbGc0TkdkRlVucExkM1ZXVGpVdlNESXlWakV2V0VWeFJtRjVWMEozYmxKU01FMTVWV3h5V1dkc1pEZGhTRGQ0ZUdGb1JrZFplVVVLV1ZsaFdXTkdPV1pFYm0xc1lXTldWVUo0VWpsd1l6UlZRbU5PWkd3MlpIQm9WbXRJWmpSUk9FUTRjMkpJUm1Wd1JWcG5Tek5YYlVKV1ZYTkNaR3hQV1FvNVFtcEdRWEkyV0VKbFNTODNTMlJEWmxWU1drWlBUVmhQYzJWMFFXZE5Ra0ZCUjJwWFZFSllUVUUwUjBFeFZXUkVkMFZDTDNkUlJVRjNTVU53UkVGUUNrSm5UbFpJVWsxQ1FXWTRSVUpVUVVSQlVVZ3ZUVUl3UjBFeFZXUkVaMUZYUWtKUlQxTXpPVlZCUVcxaVVYcFhNWEZDYTJOUVRHdFZOMFVyYUZGVVFWWUtRbWRPVmtoU1JVVkVha0ZOWjJkd2NtUlhTbXhqYlRWc1pFZFdlazFCTUVkRFUzRkhVMGxpTTBSUlJVSkRkMVZCUVRSSlFrRlJRbFp0VWs5UVEzWmpVUW80ZEdKR1MyWmlaSFJIUVVKTWJtSmljRVJxWlRCNGQwMUNaak51Tm1WclVHRTBjMlI1VW05eWJVVnlOVGMzU2k4MEsxZHRVbXMwTjJGV2VGQjRNVU00Q2xsaUsydDNZVTh4UXpkeGRXbDVObGs1TDJkUWJqaFJXakpyWmt3NVNUSkxiRUpEZDJOV1EzRnBha3g0U1ROTU1FSm1ObmxJUVZVck4yVXhaWGhHUlVJS01XYzFjM1J3Y21Wd2IyNWtVRlZMZEUxTk15dFFVM0ZqYmpnNWNHMDJjRGRWYjJ4RVdsWmlNV001UmxsSWVHRktSRW94VTFwTE4xUXZkVTUzTW1KbWNBcFBibTVFVm5CWGR6UlFVMUIwVEU0eWIxcGxUSFpqZEZock5XNUlkM1JEWmtWRFlWbDJjamxvVjBodmNUQkhRVXhVZG5OS0swdFNaMEpCVUhCSk9IUmhDbWhIVGxrMFMxcG9ORE5pU25GR0wwVjJiRE5xSzI1dGJtcHZZM2xZV0ZGVE5EWmhSbE5aTms1SFZWRTBVMHQxYzJabmFtOVVaSFkzTTJ0V1RFMDNZblFLWlRKS2IyTjFTMFpYWkVOckNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwSwpBUElfU0VSVkVSX1VSTD1odHRwczovL0U5MTBEQUE2NjgzQURBMkQzQ0FCRjgzNTM5NkJBQjlDLmdyNy5hcC1ub3J0aGVhc3QtMi5la3MuYW1hem9uYXdzLmNvbQpLOFNfQ0xVU1RFUl9ETlNfSVA9MTAuMTAwLjAuMTAKL2V0Yy9la3MvYm9vdHN0cmFwLnNoIHRlc3QtZWtzLWNsdXN0ZXIgLS1rdWJlbGV0LWV4dHJhLWFyZ3MgJy0tbm9kZS1sYWJlbHM9ZWtzLmFtYXpvbmF3cy5jb20vbm9kZWdyb3VwLWltYWdlPWFtaS0wYjFiMWQ2NTVjMTlhZmM4Mixla3MuYW1hem9uYXdzLmNvbS9jYXBhY2l0eVR5cGU9T05fREVNQU5ELGVrcy5hbWF6b25hd3MuY29tL25vZGVncm91cD10ZXN0LWVrcy1jbHVzdGVyLW5vZGVncm91cCxub2RlLmt1YmVybmV0ZXMuaW8vcm9sZT13b3JrZXIgLS1tYXgtcG9kcz0xNycgLS1iNjQtY2x1c3Rlci1jYSAkQjY0X0NMVVNURVJfQ0EgLS1hcGlzZXJ2ZXItZW5kcG9pbnQgJEFQSV9TRVJWRVJfVVJMIC0tZG5zLWNsdXN0ZXItaXAgJEs4U19DTFVTVEVSX0ROU19JUCAtLXVzZS1tYXgtcG9kcyBmYWxzZQoKLS0vLy0t"
}

resource "aws_launch_template" "test_launch_template" {
  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      delete_on_termination      = "true"
      iops                       = "0"
      # throughput                 = "0"
      # volume_initialization_rate = "0"
      volume_size                = "20"
      volume_type                = "gp2"
    }
  }

  default_version         = "1"
  disable_api_stop        = "false"
  disable_api_termination = "false"

#   iam_instance_profile {
#     name = "eks-2ecc05ed-1f40-964e-63ef-7d37607e9280"
#   }

  image_id      = "ami-0b1b1d655c19afc82"
  instance_type = "t3a.medium"

  metadata_options {
    http_put_response_hop_limit = "2"
    instance_metadata_tags      = "disabled"
  }

  name = "eks-2ecc05ed-1f40-964e-63ef-7d37607e9280"

  network_interfaces {
    device_index       = "0"
    ipv4_address_count = "0"
    ipv4_prefix_count  = "0"
    ipv6_address_count = "0"
    ipv6_prefix_count  = "0"
    network_card_index = "0"
    security_groups    = ["sg-09c0a3bf75b21cb6b"]
  }

  region = "ap-northeast-2"

  tags = {
    "eks:cluster-name"   = "test-eks-cluster"
    "eks:nodegroup-name" = "test-eks-cluster-nodegroup"
  }

  tags_all = {
    "eks:cluster-name"   = "test-eks-cluster"
    "eks:nodegroup-name" = "test-eks-cluster-nodegroup"
  }

  user_data = "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKCi0tLy8KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQ7IGNoYXJzZXQ9InVzLWFzY2lpIgojIS9iaW4vYmFzaApzZXQgLWV4CkI2NF9DTFVTVEVSX0NBPUxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVVJDVkVORFFXVXlaMEYzU1VKQlowbEpUMnM0UkVJcmVXOXZaVzkzUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkR1ZFVlVUVUpGUjBFeFZVVUtRWGhOUzJFelZtbGFXRXAxV2xoU2JHTjZRV1ZHZHpCNVRsUkJNMDFVVlhkTlZGVTFUVlJrWVVaM01IcE9WRUV6VFZSTmQwMXFRVEJOVkdSaFRVSlZlQXBGZWtGU1FtZE9Wa0pCVFZSRGJYUXhXVzFXZVdKdFZqQmFXRTEzWjJkRmFVMUJNRWREVTNGSFUwbGlNMFJSUlVKQlVWVkJRVFJKUWtSM1FYZG5aMFZMQ2tGdlNVSkJVVU16VVZkTlEwWnZORGxhVGxVNFdXRnpSbkF6YzNoaWNVb3JZbVowVDFoVVoyYzFiblZpYm5wdE1HY3lhRkpsVEZVeGRrdzNOV3R6VG5JS1kyZElXWFJLZFM5bFFWUklSMWs0WlRsWlozbFFUUzlWU1dacFJGa3pURGR3Y0RWaFJtTjRlVGhaY2xBdlozVmxWREZZYjBsWFJFZFlaRzFzVGpCV05ncDVTMEYzZG5kQlNGaHhhQzl2YzFsdlpqVkJVV2s1ZVdKWFozbHBZMlpXWVhKbVdpOTNlbmg2U1dSbVNYQlpVVEEyY1VWNVpUZzFLM2N2ZFRGUFpHUlVDbWN3T1hRMWNIVlJXbGc0TkdkRlVucExkM1ZXVGpVdlNESXlWakV2V0VWeFJtRjVWMEozYmxKU01FMTVWV3h5V1dkc1pEZGhTRGQ0ZUdGb1JrZFplVVVLV1ZsaFdXTkdPV1pFYm0xc1lXTldWVUo0VWpsd1l6UlZRbU5PWkd3MlpIQm9WbXRJWmpSUk9FUTRjMkpJUm1Wd1JWcG5Tek5YYlVKV1ZYTkNaR3hQV1FvNVFtcEdRWEkyV0VKbFNTODNTMlJEWmxWU1drWlBUVmhQYzJWMFFXZE5Ra0ZCUjJwWFZFSllUVUUwUjBFeFZXUkVkMFZDTDNkUlJVRjNTVU53UkVGUUNrSm5UbFpJVWsxQ1FXWTRSVUpVUVVSQlVVZ3ZUVUl3UjBFeFZXUkVaMUZYUWtKUlQxTXpPVlZCUVcxaVVYcFhNWEZDYTJOUVRHdFZOMFVyYUZGVVFWWUtRbWRPVmtoU1JVVkVha0ZOWjJkd2NtUlhTbXhqYlRWc1pFZFdlazFCTUVkRFUzRkhVMGxpTTBSUlJVSkRkMVZCUVRSSlFrRlJRbFp0VWs5UVEzWmpVUW80ZEdKR1MyWmlaSFJIUVVKTWJtSmljRVJxWlRCNGQwMUNaak51Tm1WclVHRTBjMlI1VW05eWJVVnlOVGMzU2k4MEsxZHRVbXMwTjJGV2VGQjRNVU00Q2xsaUsydDNZVTh4UXpkeGRXbDVObGs1TDJkUWJqaFJXakpyWmt3NVNUSkxiRUpEZDJOV1EzRnBha3g0U1ROTU1FSm1ObmxJUVZVck4yVXhaWGhHUlVJS01XYzFjM1J3Y21Wd2IyNWtVRlZMZEUxTk15dFFVM0ZqYmpnNWNHMDJjRGRWYjJ4RVdsWmlNV001UmxsSWVHRktSRW94VTFwTE4xUXZkVTUzTW1KbWNBcFBibTVFVm5CWGR6UlFVMUIwVEU0eWIxcGxUSFpqZEZock5XNUlkM1JEWmtWRFlWbDJjamxvVjBodmNUQkhRVXhVZG5OS0swdFNaMEpCVUhCSk9IUmhDbWhIVGxrMFMxcG9ORE5pU25GR0wwVjJiRE5xSzI1dGJtcHZZM2xZV0ZGVE5EWmhSbE5aTms1SFZWRTBVMHQxYzJabmFtOVVaSFkzTTJ0V1RFMDNZblFLWlRKS2IyTjFTMFpYWkVOckNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwSwpBUElfU0VSVkVSX1VSTD1odHRwczovL0U5MTBEQUE2NjgzQURBMkQzQ0FCRjgzNTM5NkJBQjlDLmdyNy5hcC1ub3J0aGVhc3QtMi5la3MuYW1hem9uYXdzLmNvbQpLOFNfQ0xVU1RFUl9ETlNfSVA9MTAuMTAwLjAuMTAKL2V0Yy9la3MvYm9vdHN0cmFwLnNoIHRlc3QtZWtzLWNsdXN0ZXIgLS1rdWJlbGV0LWV4dHJhLWFyZ3MgJy0tbm9kZS1sYWJlbHM9ZWtzLmFtYXpvbmF3cy5jb20vbm9kZWdyb3VwLWltYWdlPWFtaS0wYjFiMWQ2NTVjMTlhZmM4Mixla3MuYW1hem9uYXdzLmNvbS9jYXBhY2l0eVR5cGU9T05fREVNQU5ELGVrcy5hbWF6b25hd3MuY29tL25vZGVncm91cD10ZXN0LWVrcy1jbHVzdGVyLW5vZGVncm91cCxub2RlLmt1YmVybmV0ZXMuaW8vcm9sZT13b3JrZXIgLS1tYXgtcG9kcz0xNycgLS1iNjQtY2x1c3Rlci1jYSAkQjY0X0NMVVNURVJfQ0EgLS1hcGlzZXJ2ZXItZW5kcG9pbnQgJEFQSV9TRVJWRVJfVVJMIC0tZG5zLWNsdXN0ZXItaXAgJEs4U19DTFVTVEVSX0ROU19JUCAtLXVzZS1tYXgtcG9kcyBmYWxzZQoKLS0vLy0t"
}
