name: Feed Server CI/CD

on:
  push:
    paths: ['service/feed-server/src/**']
    branches: [main]
  pull_request:
    paths: ['service/feed-server/src/**']
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: feed-server

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4

    - name: Build with Gradle
      run: |
        cd service/feed-server/src
        ./gradlew build

    - name: Run tests
      run: |
        cd service/feed-server/src
        ./gradlew test

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write  # Changed from read to write to allow pushing changes
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      run: |
        cd service/feed-server/src
        docker buildx build --platform linux/amd64 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          --push .

    - name: Update K8s manifests
      run: |
        # Install kustomize if not already installed
        if ! command -v kustomize &> /dev/null; then
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
        fi

        # Navigate to the kustomization directory
        cd service/feed-server/k8s/overlays/dev
        
        # Update the image in kustomization
        kustomize edit set image feed-server=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
        
        # Configure git
        git config --global --add safe.directory /github/workspace
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        
        # Add and commit changes
        git add kustomization.yaml
        git diff --cached --quiet || git commit -m "ci: Update feed-server dev image to ${{ github.sha }}"
        
        # Push changes with retry logic
        for i in {1..3}; do
          if git push; then
            echo "Successfully pushed changes to repository"
            break
          else
            echo "Push attempt $i failed, pulling and retrying..."
            git pull --rebase
            sleep 5
          fi
          
          if [ $i -eq 3 ]; then
            echo "Failed to push changes after 3 attempts"
            exit 1
          fi
        done