apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1  # Dev 환경에서는 리소스 절약
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: guestbook
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master"
        - name: REDIS_SLAVE_SERVICE_HOST
          value: "redis-slave"
        resources:
          requests:
            memory: "32Mi"  # Dev 환경 리소스 축소
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m" 