apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-config
    app.kubernetes.io/part-of: argo-rollouts
data:
  # Argo Rollouts Controller 설정
  # 자세한 설정 옵션: https://argo-rollouts.readthedocs.io/en/stable/features/controller/
  
  # 메트릭 제공자 설정 (Prometheus)
  # metrics.yaml: |
  #   providers:
  #     - name: prometheus
  #       type: prometheus
  #       url: http://prometheus.monitoring.svc.cluster.local:9090
  
  # 알림 설정
  # notifications.yaml: |
  #   service:
  #     slack:
  #       token: $slack-token
  
  # 트래픽 관리 설정 (ALB, Istio 등)
  # traffic-management.yaml: |
  #   trafficRouterPlugins:
  #     - name: "argoproj-labs/rollouts-plugin-trafficrouter-aws-app-mesh"
  #       location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-aws-app-mesh/releases/download/v0.1.0/aws-app-mesh-trafficrouter-linux-amd64"

# argo-rollouts-notification-config는 공식 매니페스트에 없으므로 제거
# 필요시 별도 리소스로 생성 