apiVersion: v1
kind: ResourceQuota
metadata:
  name: argo-rollouts-resource-quota
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-resource-quota
    environment: dev
spec:
  hard:
    # 컴퓨팅 리소스
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    
    # 스토리지 리소스
    requests.storage: "5Gi"
    persistentvolumeclaims: "3"
    
    # 객체 수 제한
    count/deployments.apps: "5"
    count/services: "10"
    count/configmaps: "15"
    count/secrets: "10"
    count/pods: "10"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: argo-rollouts-limit-range
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-limit-range
    environment: dev
spec:
  limits:
    # 컨테이너 기본값
    - type: Container
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
    
    # Pod 제한
    - type: Pod
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
    
    # PVC 제한  
    - type: PersistentVolumeClaim
      max:
        storage: "2Gi"
      min:
        storage: "1Gi"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argo-rollouts-pdb
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-pdb
    environment: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argo-rollouts-network-policy
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-network-policy
    environment: dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Dashboard 접근 허용
    - from:
        - namespaceSelector:
            matchLabels:
              name: kube-system  # ALB Controller
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx  # Nginx Ingress (대안)
      ports:
        - protocol: TCP
          port: 3100
    # 메트릭 수집 허용 (Prometheus)
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8090
  egress:
    # Kubernetes API 접근
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # DNS 해석
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53 